### ISSUE TITLE
Accessory is out of compliance

### ISSUE THREAD

**Issue by oleksiikutuzov** [HomeSpan/HolidayLights#2]
When trying to add this accessory to HomeKit, it says "Unable to add accessory. Accessory is out of compliance". The sketch was not modified, tried to add it from an iPhone running the latest iOS beta. 
[log.txt](https://github.com/HomeSpan/HolidayLights/files/8105873/log.txt)

![IMG_9366](https://user-images.githubusercontent.com/8535871/154881836-5d18ce54-4300-4448-9054-b8305292e593.PNG)

**Comment by HomeSpan** [comment]
This is puzzling.  Based on your log file, the problem is here:

> Characteristic Selector(1):  IID=15, UUID="00000001 - 0001 - 0001 - 0001 - 46637266EA00", Range=[1,5] (restored) *** WARNING!  Service does not support this Characteristic. ***

For some reason there are spaces between the dashes in this custom UUID, which will be rejected by the Home App.  Did you copy the code through the clipboard perhaps, or use a formatting tool on the code?  The sketch itself contains the following in line 57:

```CUSTOM_CHAR(Selector, 00000001-0001-0001-0001-46637266EA00, PR+PW+EV, UINT8, 1, 1, 5, false);      // create Custom Characteristic to "select" special effects via Eve App```

As you can see, there are no spaces between the dashes in the code.  Not sure why this is being converted to a longer string with spaces between the dashes.

**Comment by oleksiikutuzov** [comment]
Yes, indeed, it was because of a formatter. Thanks a lot!
